### ISSUE TITLE
Uncaught (in promise) DOMException on https://gridsome.org/docs/faq/

### ISSUE THREAD

**Issue by minho42** [gridsome/gridsome.org#244]
When visited [https://gridsome.org/docs/faq](https://gridsome.org/docs/faq)
I get this error on my console tab.

```
Uncaught (in promise) DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
    at Object.appendChild (https://gridsome.org/assets/js/app.f8d10897.js:7:40661)
    at d (https://gridsome.org/assets/js/app.f8d10897.js:7:53233)
    at l (https://gridsome.org/assets/js/app.f8d10897.js:7:52970)
    at h (https://gridsome.org/assets/js/app.f8d10897.js:7:53316)
    at A (https://gridsome.org/assets/js/app.f8d10897.js:7:56658)
    at a.__patch__ (https://gridsome.org/assets/js/app.f8d10897.js:7:57016)
    at a.t._update (https://gridsome.org/assets/js/app.f8d10897.js:7:34372)
    at a.r (https://gridsome.org/assets/js/app.f8d10897.js:7:64308)
    at dn.get (https://gridsome.org/assets/js/app.f8d10897.js:7:26630)
    at new dn (https://gridsome.org/assets/js/app.f8d10897.js:7:26548)

```
Above error doesn't affect at all for this FAQ page alone.

However, if I visit another link (side menu links or "Dev tools" at the bottom of the page) from this page, I get another error message on the console.

```
app.f8d10897.js:7 TypeError: n.setAttribute is not a function
    at Array.mr (app.f8d10897.js:7)
    at j (app.f8d10897.js:7)
    at app.f8d10897.js:7
    at j (app.f8d10897.js:7)
    at app.f8d10897.js:7
    at j (app.f8d10897.js:7)
    at app.f8d10897.js:7
    at j (app.f8d10897.js:7)
    at app.f8d10897.js:7
    at j (app.f8d10897.js:7)

```

From here, routing doesn't work.
It doesn't load the content but only URLs change.

**Comment by zacnomore** [comment]
Hello!

I attempted to reproduce this issue in 
MacOS Chrome 76.0.3809.132
MacOS Firefox 70.0b6
Android Chrome 76.0.3809.132

But was unable to. This bug may have been fixed or it could be a little sneaky!

**Comment by minho42** [comment]
Hi @zacnomore,
I can't reproduce it anymore either. 
Guess it's fixed.
I'll close this. 
Thanks.
