### ISSUE TITLE
Error: Schema must contain uniquely named types but contains multiple types named "RemarkHeadingLevels".

### ISSUE THREAD

**Issue by santoshdahal2016** [gridsome/gridsome.org#299]
I encountered this error during running newly fetch projects. 
OS: Ubuntu 18.04

**Comment by carloscabral** [comment]
Same here.

**Comment by weaversam8** [comment]
I also encountered this issue on running `gridsome develop` on the `gridsome.org` repository.

**Comment by as3k** [comment]
I had the same problem earlier today. I removed `node_modules` and then **installed with yarn** instead of **npm**. After installing with yarn everything worked fine.

**Comment by tiptronic** [comment]
nope - same thing here... swapping npw with yarn didn't help

**Comment by stereokai** [comment]
I'm stuck with this too

**Comment by TerabyteTiger** [comment]
I haven't run into this on Windows 10 using PowerShell or CMD - Can someone provide additional details so it's easier to look into this?  

- Which Gridsome CLI Version? 
- Post the error message with context for source of the error
- Is this happening on projects other than `Gridsome.org`? 

Thanks!

**Comment by stereokai** [comment]
@TerabyteTiger I am getting this error on Mac. I also tagged you in a ~duplicate~ similar issue. Thank you for looking into this!

## Description
```console
Gridsome v0.7.19

Initializing plugins...
Load sources - 0s
Error: Schema must contain uniquely named types but contains multiple types named "Mutation".
    at typeMapReducer (project/node_modules/.pnpm/graphql@14.7.0/node_modules/graphql/type/schema.js:262:13)
    at Array.reduce (<anonymous>)
    at new GraphQLSchema (project/node_modules/.pnpm/graphql@14.7.0/node_modules/graphql/type/schema.js:145:28)
    at SchemaComposer.buildSchema (project/node_modules/.pnpm/graphql-compose@7.18.1_graphql@14.7.0/node_modules/graphql-compose/lib/SchemaComposer.js:153:12)
    at Schema.buildSchema (project/node_modules/.pnpm/gridsome@0.7.19/node_modules/gridsome/lib/app/Schema.js:35:35)
    at Plugins.createSchema (project/node_modules/.pnpm/gridsome@0.7.19/node_modules/gridsome/lib/app/Plugins.js:94:22)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
### Steps to reproduce
In `gridsome.config.js`:
```js
module.exports = {
  plugins: [
    {
      use: 'gridsome-source-graphql',
      options: {
        url: 'http://localhost:8888/graphql',
        fieldName: 'gqlFieldName',
        typeName: 'gqlTypeName',
      },
    },
  ],
}
```
`url` is pointing to a local GraphQL server (verified to be working correctly and consumable)

### Expected result

Gridsome should consume the GraphQL properly and load the app

### Actual result

Gridsome throws the error above and exits, does not start app

### Environment

```
  System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
  Binaries:
    Node: 12.18.2 - ~/.nvm/versions/node/v12.18.2/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v12.18.2/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v12.18.2/bin/npm
  Browsers:
    Chrome: 84.0.4147.89
    Firefox: 77.0.1
    Safari: 13.1.2
  npmPackages:
    gridsome: ^0.7.0 => 0.7.19
    gridsome-source-graphql: ~1.0.2 => 1.0.2
```

**Comment by TerabyteTiger** [comment]
Thanks for the very detailed reponse @stereokai! 

To possibly help narrow it down further, does this occur when using [`@gridsome/source-graphql`](https://github.com/gridsome/gridsome/tree/master/packages/source-graphql)? Or only with [`gridsome-source-graphql`](https://github.com/waxapi/gridsome-source-graphql)?

**Comment by stereokai** [comment]
I wasn't aware of `@gridsome/source-graphql`, let me try it out! :)

**Comment by stereokai** [comment]
@TerabyteTiger I cleared my npm cache, completely erased node_modules, and ran `npm i` for a fresh installation.

Now I'm getting this:
```console
Gridsome v0.7.19

Initializing plugins...
Load sources - 0s
Error: Cannot use GraphQLList "[gqlTypeName_Log]" from another module or realm.

Ensure that there is only one instance of "graphql" in the node_modules
directory. If different versions of "graphql" are the dependencies of other
relied on modules, use "resolutions" to ensure only one version is installed.

https://yarnpkg.com/en/docs/selective-version-resolutions

Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data from one
version used in the function from another could produce confusing and
spurious results.
    at instanceOf (project/node_modules/gridsome/node_modules/graphql/jsutils/instanceOf.js:28:13)
    at isListType (project/node_modules/gridsome/node_modules/graphql/type/definition.js:181:34)
    at isWrappingType (project/node_modules/gridsome/node_modules/graphql/type/definition.js:364:10)
    at getNamedType (project/node_modules/gridsome/node_modules/graphql/type/definition.js:423:12)
    at typeMapReducer (project/node_modules/gridsome/node_modules/graphql/type/schema.js:257:48)
    at typeMapReducer (project/node_modules/gridsome/node_modules/graphql/type/schema.js:286:20)
    at typeMapReducer (project/node_modules/gridsome/node_modules/graphql/type/schema.js:286:20)
    at Array.reduce (<anonymous>)
    at new GraphQLSchema (project/node_modules/gridsome/node_modules/graphql/type/schema.js:145:28)
    at NamespaceUnderFieldTransform.transformSchema (project/node_modules/@gridsome/source-graphql/transforms.js:57:12)
    at project/node_modules/graphql-tools/dist/transforms/transforms.js:11:54
    at Array.reduce (<anonymous>)
    at Object.applySchemaTransforms (project/node_modules/graphql-tools/dist/transforms/transforms.js:10:23)
    at transformSchema (project/node_modules/graphql-tools/dist/transforms/transformSchema.js:17:27)
    at GraphQLSource.namespaceSchema (project/node_modules/@gridsome/source-graphql/index.js:72:12)
    at project/node_modules/@gridsome/source-graphql/index.js:50:43
```

This is my `package.json`:
```json
{
  "name": "project",
  "private": true,
  "scripts": {
    "build": "gridsome build",
    "develop": "gridsome develop",
    "explore": "gridsome explore"
  },
  "dependencies": {
    "@gridsome/source-graphql": "~0.1.0",
    "gridsome": "^0.7.0"
  }
}

```

**Comment by TerabyteTiger** [comment]
That seems super weird - does this happen to be a public repo?

**Comment by TerabyteTiger** [comment]
This is super weird. I have both packages working without issue - Windows 10, PowerShell. 

I started with the `@gridsome` package, then cleared everything out and installed `gridsome-source-graphql`. 

These were my files - 

## `@gridsome/source-graphql`

```js
// gridsome.config.js

module.exports = {
  siteName: "Gridsome",
  plugins: [
    {
      use: "@gridsome/source-graphql",
      options: {
        url: "https://rickandmortyapi.com/graphql/",
        fieldName: "rickandmorty",
        typeName: "RAM",
      },
    },
  ],
};
```

```gql
query {
   rickandmorty{
    characters {
      results {
        name
      }
    }
  }
}
```

```json
// Package.json

{
  "name": "ql-test",
  "private": true,
  "scripts": {
    "build": "gridsome build",
    "develop": "gridsome develop",
    "explore": "gridsome explore"
  },
  "dependencies": {
    "@gridsome/source-graphql": "^0.1.0",
    "gridsome": "^0.7.0"
  }
}
```

## `gridsome-source-graphql`

```js
// gridsome.config.js

module.exports = {
  siteName: "Gridsome",
  plugins: [
    {
      use: "gridsome-source-graphql",
      options: {
        url: "https://rickandmortyapi.com/graphql/",
        fieldName: "rickandmorty",
        typeName: "RAM",
      },
    },
  ],
};

```

```gql
query {
   characters {
    results {
      name
    }
  }
}
```

```json
// Package.json

{
  "name": "ql-test",
  "private": true,
  "scripts": {
    "build": "gridsome build",
    "develop": "gridsome develop",
    "explore": "gridsome explore"
  },
  "dependencies": {
    "gridsome": "^0.7.0",
    "gridsome-source-graphql": "^1.0.2"
  }
}

```

The only thing that stands out with your project @stereokai is that your graphQL is also on localhost - but I _really_ don't think that's the cause of the issue. 

Maybe someone with a Bash terminal can check if these files work for them?

**Comment by stereokai** [comment]
Using your settings, I'm now getting this:

```console
Initializing plugins...
Load sources - 0s
Error: Cannot use GraphQLObjectType "RAM_Character" from another module or realm.

Ensure that there is only one instance of "graphql" in the node_modules
directory. If different versions of "graphql" are the dependencies of other
relied on modules, use "resolutions" to ensure only one version is installed.

https://yarnpkg.com/en/docs/selective-version-resolutions

Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data from one
version used in the function from another could produce confusing and
spurious results.
```

**Comment by jackoconnor21** [comment]
Has anybody been able to figure this out? I'm using AWS Amplify (AppSync GraphQL) and i'm getting the same issue.
`Schema must contain uniquely named types but contains multiple types named "Mutation"`

I would really appreciate any help here.
